import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.pais.createMany({
    data: [
      {
        nome: 'Brasil',
        continente: 'América do Sul',
        populacao: 213000000,
        idioma: 'Português',
        curiosidade: 'Maior país da América do Sul.',
      },
      {
        nome: 'Argentina',
        continente: 'América do Sul',
        populacao: 45000000,
        idioma: 'Espanhol',
        curiosidade: 'Conhecida por seu tango e carne.',
      },
      {
        nome: 'Chile',
        continente: 'América do Sul',
        populacao: 19000000,
        idioma: 'Espanhol',
        curiosidade: 'Possui o deserto mais seco do mundo.',
      },
      {
        nome: 'Uruguai',
        continente: 'América do Sul',
        populacao: 3500000,
        idioma: 'Espanhol',
        curiosidade: 'Um dos países mais seguros da América Latina.',
      },
      {
        nome: 'Paraguai',
        continente: 'América do Sul',
        populacao: 7100000,
        idioma: 'Espanhol',
        curiosidade: 'Grande parte da população fala Guarani.',
      },
      {
        nome: 'Estados Unidos',
        continente: 'América do Norte',
        populacao: 331000000,
        idioma: 'Inglês',
        curiosidade: 'Maior economia do mundo.',
      },
      {
        nome: 'Canadá',
        continente: 'América do Norte',
        populacao: 38000000,
        idioma: 'Inglês e Francês',
        curiosidade: 'Segundo maior país territorial do mundo.',
      },
      {
        nome: 'México',
        continente: 'América do Norte',
        populacao: 128000000,
        idioma: 'Espanhol',
        curiosidade: 'Origem da cultura maia e asteca.',
      },
      {
        nome: 'Japão',
        continente: 'Ásia',
        populacao: 125000000,
        idioma: 'Japonês',
        curiosidade: 'Conhecido por sua alta tecnologia.',
      },
      {
        nome: 'China',
        continente: 'Ásia',
        populacao: 1400000000,
        idioma: 'Mandarim',
        curiosidade: 'Maior população do mundo.',
      },
      {
        nome: 'Coreia do Sul',
        continente: 'Ásia',
        populacao: 52000000,
        idioma: 'Coreano',
        curiosidade: 'Berço do K-pop.',
      },
      {
        nome: 'Índia',
        continente: 'Ásia',
        populacao: 1380000000,
        idioma: 'Hindi',
        curiosidade: 'Segundo país mais populoso do mundo.',
      },
      {
        nome: 'Indonésia',
        continente: 'Ásia',
        populacao: 273000000,
        idioma: 'Indonésio',
        curiosidade: 'Maior arquipélago do planeta.',
      },
      {
        nome: 'Austrália',
        continente: 'Oceania',
        populacao: 26000000,
        idioma: 'Inglês',
        curiosidade: 'Tem mais cangurus que pessoas.',
      },
      {
        nome: 'Nova Zelândia',
        continente: 'Oceania',
        populacao: 5000000,
        idioma: 'Inglês',
        curiosidade: 'Cenário de Senhor dos Anéis.',
      },
      {
        nome: 'Papua Nova Guiné',
        continente: 'Oceania',
        populacao: 9000000,
        idioma: 'Inglês e Tok Pisin',
        curiosidade: 'Abriga mais de 800 línguas.',
      },
      {
        nome: 'Alemanha',
        continente: 'Europa',
        populacao: 83000000,
        idioma: 'Alemão',
        curiosidade: 'Maior economia da Europa.',
      },
      {
        nome: 'França',
        continente: 'Europa',
        populacao: 67000000,
        idioma: 'Francês',
        curiosidade: 'País mais visitado do mundo.',
      },
      {
        nome: 'Itália',
        continente: 'Europa',
        populacao: 60000000,
        idioma: 'Italiano',
        curiosidade: 'Berço do Império Romano.',
      },
      {
        nome: 'Espanha',
        continente: 'Europa',
        populacao: 47000000,
        idioma: 'Espanhol',
        curiosidade: 'Famosa pela dança flamenca.',
      },
      {
        nome: 'Portugal',
        continente: 'Europa',
        populacao: 10000000,
        idioma: 'Português',
        curiosidade: 'Possui o menor tempo médio de sol na UE.',
      },
      {
        nome: 'Reino Unido',
        continente: 'Europa',
        populacao: 68000000,
        idioma: 'Inglês',
        curiosidade: 'Lar da monarquia britânica.',
      },
      {
        nome: 'Holanda',
        continente: 'Europa',
        populacao: 17000000,
        idioma: 'Holandês',
        curiosidade: 'Famosa pelos moinhos e tulipas.',
      },
      {
        nome: 'Bélgica',
        continente: 'Europa',
        populacao: 11500000,
        idioma: 'Francês e Holandês',
        curiosidade: 'Criadora das batatas fritas.',
      },
      {
        nome: 'Suécia',
        continente: 'Europa',
        populacao: 10000000,
        idioma: 'Sueco',
        curiosidade: 'País de origem do Spotify.',
      },
      {
        nome: 'Noruega',
        continente: 'Europa',
        populacao: 5400000,
        idioma: 'Norueguês',
        curiosidade: 'Alta qualidade de vida.',
      },
      {
        nome: 'Finlândia',
        continente: 'Europa',
        populacao: 5500000,
        idioma: 'Finlandês',
        curiosidade: 'O país mais feliz do mundo (2023).',
      },
      {
        nome: 'Dinamarca',
        continente: 'Europa',
        populacao: 5800000,
        idioma: 'Dinamarquês',
        curiosidade: 'Conhecida pela filosofia Hygge.',
      },
      {
        nome: 'Suíça',
        continente: 'Europa',
        populacao: 8600000,
        idioma: 'Alemão e Francês',
        curiosidade: 'Famosa pelos chocolates e relógios.',
      },
      {
        nome: 'Áustria',
        continente: 'Europa',
        populacao: 9000000,
        idioma: 'Alemão',
        curiosidade: 'Berço de Mozart.',
      },
      {
        nome: 'Polônia',
        continente: 'Europa',
        populacao: 38000000,
        idioma: 'Polonês',
        curiosidade: 'Forte tradição católica.',
      },
      {
        nome: 'Grécia',
        continente: 'Europa',
        populacao: 11000000,
        idioma: 'Grego',
        curiosidade: 'Berço da democracia.',
      },
      {
        nome: 'Turquia',
        continente: 'Europa/Ásia',
        populacao: 82000000,
        idioma: 'Turco',
        curiosidade: 'País dividido entre dois continentes.',
      },
      {
        nome: 'Egito',
        continente: 'África',
        populacao: 100000000,
        idioma: 'Árabe',
        curiosidade: 'Lar das pirâmides de Gizé.',
      },
      {
        nome: 'África do Sul',
        continente: 'África',
        populacao: 60000000,
        idioma: 'Diversos',
        curiosidade: 'Possui 11 línguas oficiais.',
      },
      {
        nome: 'Nigéria',
        continente: 'África',
        populacao: 206000000,
        idioma: 'Inglês',
        curiosidade: 'País mais populoso da África.',
      },
      {
        nome: 'Quênia',
        continente: 'África',
        populacao: 53000000,
        idioma: 'Suaili',
        curiosidade: 'Famoso pelos safáris.',
      },
      {
        nome: 'Marrocos',
        continente: 'África',
        populacao: 36000000,
        idioma: 'Árabe',
        curiosidade: 'Cidade azul Chefchaouen é mundialmente conhecida.',
      },
      {
        nome: 'Tunísia',
        continente: 'África',
        populacao: 12000000,
        idioma: 'Árabe',
        curiosidade: 'Local onde começou a Primavera Árabe.',
      },
      {
        nome: 'Argélia',
        continente: 'África',
        populacao: 43000000,
        idioma: 'Árabe',
        curiosidade: 'Maior país da África em território.',
      },
      {
        nome: 'Etiópia',
        continente: 'África',
        populacao: 114000000,
        idioma: 'Amárico',
        curiosidade: 'Nunca foi colonizada.',
      },
      {
        nome: 'Gana',
        continente: 'África',
        populacao: 31000000,
        idioma: 'Inglês',
        curiosidade: 'Um dos países mais estáveis da África.',
      },
      {
        nome: 'Peru',
        continente: 'América do Sul',
        populacao: 33000000,
        idioma: 'Espanhol',
        curiosidade: 'Lar de Machu Picchu.',
      },
      {
        nome: 'Colômbia',
        continente: 'América do Sul',
        populacao: 51000000,
        idioma: 'Espanhol',
        curiosidade: 'Grande diversidade de fauna e flora.',
      },
      {
        nome: 'Venezuela',
        continente: 'América do Sul',
        populacao: 28000000,
        idioma: 'Espanhol',
        curiosidade: 'Possui o maior salto d’água do mundo.',
      },
      {
        nome: 'Bolívia',
        continente: 'América do Sul',
        populacao: 11500000,
        idioma: 'Espanhol',
        curiosidade: 'Possui o Salar de Uyuni.',
      },
      {
        nome: 'Equador',
        continente: 'América do Sul',
        populacao: 17500000,
        idioma: 'Espanhol',
        curiosidade: 'Linha do Equador cruza o país.',
      },
      {
        nome: 'Costa Rica',
        continente: 'América Central',
        populacao: 5000000,
        idioma: 'Espanhol',
        curiosidade: 'Não possui exército.',
      },
      {
        nome: 'Panamá',
        continente: 'América Central',
        populacao: 4300000,
        idioma: 'Espanhol',
        curiosidade: 'Famoso pelo Canal do Panamá.',
      },
    ],
  });

  console.log('🌍 50 países criados com sucesso!');
}

main()
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());
